# Generated by Django 4.2.26 on 2025-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
